Update walletconnect v2
Onyx-Protocol/onyx-interface pull request #75
Opened 2023-08-07 16:23 UTC by r2moon

## Trello ticket(s)

#### #9

## Changes

Migrate Wallet Connect V1 to V2

2023-08-12 02:13 UTC, MerdyNumber1 requested changes

2023-08-12 02:13 UTC, MerdyNumber1 commented on src/clients/web3/walletconnectV2.ts
> +export const URI_AVAILABLE = 'URI_AVAILABLE';
What is it variable? Why this value is URI_AVAILABLE?

2023-08-12 02:13 UTC, MerdyNumber1 commented on package.json
> +      "not dead",
You just updated browser-list or it's required for wallet connect v2?

2023-08-31 00:12 UTC, r2moon commented on package.json
> +      "not dead",
Yeah, without that, there was the build issue.

2023-09-12 21:20 UTC, merged